### ISSUE TITLE
StyledView body() crash in 1.9.0

### ISSUE THREAD

**Issue by ipedro** [nathantannar4/Engine#17]
The improvements in `PrimitiveView` done in 1.9.0 unfortunately broke `StyledView`. They are expected to have valid `Body`, but the new constraint casts it as `Never`, so body falls through to `bodyError()`. The problem is easy to reproduce.

I raised a PR proposing a fix. https://github.com/nathantannar4/Engine/pull/16

**Comment by nathantannar4** [comment]
Thanks for flagging! Fixed in 1.9.2, I believe the best fix is to revert. `_DefaultStyledView` is just used to dance around Swift macro limitations to make a nicer API. `StyledView` shouldn't have been made `PrimitiveView`

**Comment by ipedro** [comment]
Yeah, makes sense! Now I realize it doesn't even use the GraphInput extensions.

Thanks for the quick fix! 🙂
