### ISSUE TITLE
EngineCore binary...

### ISSUE THREAD

**Issue by woolie** [nathantannar4/Engine#2]
I'm trying to learn from the code you have here as it seems very much like things I want to learn about.
I can only go so far though as, as far as I can see, there is a dependency on EngineCore, for which there is no source code.

Are there plans to release EngineCore as well? Thanks in advance for any insight.

**Comment by nathantannar4** [comment]
Hey, thanks for your interest! At this time, I don't plan on releasing all of `EngineCore`, but there are some aspects that could be moved out into `Engine`. 

For some insight, `EngineCore` contains C code and "unsafe" low level Swift code. SPM doesn't support projects that mix in C code, so for a technical reason there must always be binary dependency.

Is there a particular aspect I can help provide more insight on?

**Comment by woolie** [comment]
There are simple workarounds for the mixed language packages, but yeah, a pain.
I was wondering how the _ViewInputsBridgeModifier was implemented.

This is how I do the mixed C and Swift package:

let package = Package(
	name: "SwiftOSC",
	platforms: [.macOS(.v12), .iOS(.v16)],

	products: [
		.library(
			name: "SwiftOSC",
			targets: ["SwiftOSC"]
		),
	],

	targets: [
		.target(
			name: "YUDPSocket",
			path: "Source/YUDPSocket"
		),
		.target(
			name: "SwiftOSC",
			dependencies: [.target(name: "YUDPSocket")],
			path: "Source/SwiftOSC"
		),
		.testTarget(
			name: "SwiftOSC-Tests",
			dependencies: [
				"SwiftOSC",
			]
		)
	],

	swiftLanguageVersions: [.v5]
)

Where the C code is in another folder than the Swift files.
Thanks for responding.



W.

**Comment by nathantannar4** [comment]
`EngineCore` has C and Swift code so it has to be its own binary.

`_ViewInputsBridgeModifier` resets all of the "View Styling", so that if you apply a `.buttonStyle` or even a custom style with the style APIs of Engine, they are not carried forward to the next `UIHostingController` that is presented. This is to match how SwiftUIs existing presentation modifiers work.
