### ISSUE TITLE
Support for Environment Visitor

### ISSUE THREAD

**Issue by Wouter01** [nathantannar4/Engine#6]
I was wondering if it would be possible to have extract values from the Environment, just like this library made that possible for view traits?

It would be awesome if that would be possible, as Environment contains many useful but hidden values.

Thank you!

**Comment by nathantannar4** [comment]
It's certainly possible, but making the API safe is tricky. The hidden values could be any custom type. So while returning them as `Any` is easy, it would be the responsibility of the caller to handle figuring out what type it actually is.

Any environment value in particular you had in mind?

**Comment by Wouter01** [comment]
> It's certainly possible, but making the API safe is tricky. The hidden values could be any custom type. So while returning them as `Any` is easy, it would be the responsibility of the caller to handle figuring out what type it actually is.
> 
> Any environment value in particular you had in mind?

Yeah, I noticed that earlier when working with the trait visitor. Functions should be doable I would guess, custom types a bit less.

A useful environment value I saw was the following:
```
EnvironmentPropertyKey<EnvironmentObjectKey<SceneBridge>> = Optional(SceneBridge: window = Optional(<SwiftUI.AppKitWindow: 0x10f73a450>))
```

Getting a hold of the current window still requires awkward workarounds at the moment, and I'm wondering if this environment key would make things much easier.

Slightly off-topic, but does the repo accept PRs that add extra predefined trait accessors? I have some to support SwiftUI's `onInsert`, `onDelete`, which seem useful in general

**Comment by nathantannar4** [comment]
I would encourage not trying to read hidden keys the environment if what you're trying to accomplish can be done another way. You could run into a variety of issue and may not be a maintainable approach. 

If you're trying to read the window, I'd recommend a UIViewReprsentable to observe the window. I've had great success with that approach. 

See the following and its use in WindowLinkModifier:
https://github.com/nathantannar4/Transmission/blob/main/Sources/Transmission/Sources/Supporting%20Files/WindowReader.swift

**Comment by nathantannar4** [comment]
RE: The trait accessors. Do you mean to add a convenience accessor in AnyVariadicView?

**Comment by Wouter01** [comment]
> If you're trying to read the window, I'd recommend a UIViewReprsentable to observe the window. I've had great success with that approach.

That approach does indeed work, but it's not perfect. For example, disabling a window button using this method sometimes has a split-second delay. It's mostly out of curiosity that I'd like to see if that can be resolved by using this other method. Now that EngineCore has been open sourced (which I really appreciate!), I can have a closer look myself.

**Comment by Wouter01** [comment]
> RE: The trait accessors. Do you mean to add a convenience accessor in AnyVariadicView?

Exactly! For example:

```swift
extension AnyVariadicView.Subview {
    var onMove: ((IndexSet, Int) -> Void)? {
        self["s7SwiftUI14OnMoveTraitKeyV", as: ((IndexSet, Int) -> Void).self]
    }
}
```

**Comment by nathantannar4** [comment]
> For example, disabling a window button

What do you mean by this? Just curious as maybe I could improve something.

**Comment by Wouter01** [comment]
> > For example, disabling a window button
> 
> What do you mean by this? Just curious as maybe I could improve something.

I'm referring to [this](https://developer.apple.com/documentation/appkit/nswindow/1419173-standardwindowbutton) method of NSWindow, with which you're able to access the traffic light buttons of the window.

I've tried some things myself, and it looks like accessing the NSWindow instance from the environment doesn't provide any benefits compared to the UIViewRepresentable approach. Accessing most environment keys also proved to be harder than accessing trait keys, as the types are nested and I couldn't resolve the whole mangled name correctly.

**Comment by nathantannar4** [comment]
Supported in 1.5.0
