### ISSUE TITLE
XCode Cloud build+archive error: Target 'EngineMacros' must be enabled before it can be used.

### ISSUE THREAD

**Issue by sindreoyen** [nathantannar4/Engine#8]
<img width="413" alt="image" src="https://github.com/nathantannar4/Engine/assets/31347883/3a458243-a689-4289-9cbb-b9dd914b4d77">

When building the application in the xcode cloud, the EngineMacros target causes a fatal error, in turn causing the builds to crash.

**Comment by nathantannar4** [comment]
This is intended behaviour with macros. I have the solution listed in the README

> Xcode Cloud / Github Actions / Fastlane / CI

Engine includes a Swift macro, which requires user validation to enable or the build will fail. When configuring your CI, pass the flag -skipMacroValidation to xcodebuild to fix this.
